In [78]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [79]:
# Load the Excel file into a variable
transactions = pd.DataFrame(pd.read_excel("KPMG_VI_New_raw_data_update_final.xlsx", sheet_name=1))
new_customers_list = pd.DataFrame(pd.read_excel("KPMG_VI_New_raw_data_update_final.xlsx", sheet_name=2))
customer_demographic = pd.DataFrame(pd.read_excel("KPMG_VI_New_raw_data_update_final.xlsx", sheet_name=3))
customer_address = pd.DataFrame(pd.read_excel("KPMG_VI_New_raw_data_update_final.xlsx", sheet_name=4))

<ipython-input-79-6e689c35e69d>:3: FutureWarning: Inferring datetime64[ns] from data containing strings is deprecated and will be removed in a future version. To retain the old behavior explicitly pass Series(data, dtype=datetime64[ns])
  new_customers_list = pd.DataFrame(pd.read_excel("KPMG_VI_New_raw_data_update_final.xlsx", sheet_name=2))
<ipython-input-79-6e689c35e69d>:4: FutureWarning: Inferring datetime64[ns] from data containing strings is deprecated and will be removed in a future version. To retain the old behavior explicitly pass Series(data, dtype=datetime64[ns])
  customer_demographic = pd.DataFrame(pd.read_excel("KPMG_VI_New_raw_data_update_final.xlsx", sheet_name=3))


Transactions

In [80]:
#transactions.info()

In [81]:
#transactions.head(5)

In [82]:
#transactions.describe()

In [83]:
#sns.pairplot(transactions)

## listing  and standar prices are perfectly correlated
## customer_id, product_line, product_class, product_size, list_price, standard_cost

New customer list

In [84]:
#new_customers_list.info()

In [85]:
#new_customers_list.describe()

In [86]:
#sns.pairplot(new_customers_list)

In [87]:
#new_customers_list.head()

## gender, past_3_years_bike_related_purchases, DOB, job_industry_category, wealth_segment, owns_car, tenure, address, postcode, state, country, property_valuation, Rank, Value

customer demographic

In [88]:
#customer_demographic.describe()

In [89]:
#customer_demographic.info()

In [90]:
#customer_demographic.head()

## gender, past_3_years_bike_related_purchases, DOB, job_industry_category, wealth_segment, owns_car, tenure, customer_id


customer_address

In [91]:
#customer_address.describe()

In [92]:
#customer_address.info()

In [93]:
#customer_address.head()

In [94]:
customer_address['country'].unique()

array(['Australia'], dtype=object)

## convert states -  only 3
## address, postcode, state, property_valuation

In [95]:
#sns.histplot(customer_address)

In [96]:
customers = pd.merge(customer_demographic, customer_address, how='inner', on='customer_id')

In [97]:
transactions.drop(columns=['transaction_id', 'product_id', 'transaction_date', 'online_order', 'order_status', 'product_first_sold_date'], axis=1, inplace=True)

In [98]:
transactions.head(3)

customer_id          brand product_line product_class product_size  \
0         2950          Solex     Standard        medium       medium   
1         3120  Trek Bicycles     Standard        medium        large   
2          402     OHM Cycles     Standard           low       medium   

   list_price  standard_cost  
0       71.49          53.62  
1     2091.47         388.92  
2     1793.43         248.82

In [104]:
transactions = transactions.groupby('customer_id')

In [99]:
customers = pd.merge(customers, transactions, how='inner', on='customer_id')

In [100]:
customers.head(3)

customer_id first_name  last_name gender  \
0            1    Laraine  Medendorp      F   
1            1    Laraine  Medendorp      F   
2            1    Laraine  Medendorp      F   

   past_3_years_bike_related_purchases        DOB            job_title  \
0                                   93 1953-10-12  Executive Secretary   
1                                   93 1953-10-12  Executive Secretary   
2                                   93 1953-10-12  Executive Secretary   

  job_industry_category wealth_segment deceased_indicator  ... postcode  \
0                Health  Mass Customer                  N  ...     2016   
1                Health  Mass Customer                  N  ...     2016   
2                Health  Mass Customer                  N  ...     2016   

             state    country property_valuation          brand product_line  \
0  New South Wales  Australia                 10     OHM Cycles     Standard   
1  New South Wales  Australia                 10          Solex     Standard   
2  New South Wales  Australia                 10  Trek Bicycles         Road   

  product_class  product_size list_price standard_cost  
0        medium        medium     235.63        125.07  
1        medium        medium    1577.53        826.51  
2           low         small    1720.70       1531.42  

[3 rows x 24 columns]

## clean customers

In [101]:
customers.drop(columns=['first_name', 'last_name', 'job_title','default','address','country'], axis=1, inplace=True)

In [102]:
customers.set_index('customer_id', inplace=True)

In [27]:
customers.dropna(inplace=True)

In [103]:
customers.head(10)

gender  past_3_years_bike_related_purchases        DOB  \
customer_id                                                          
1                F                                   93 1953-10-12   
1                F                                   93 1953-10-12   
1                F                                   93 1953-10-12   
1                F                                   93 1953-10-12   
1                F                                   93 1953-10-12   
1                F                                   93 1953-10-12   
1                F                                   93 1953-10-12   
1                F                                   93 1953-10-12   
1                F                                   93 1953-10-12   
1                F                                   93 1953-10-12   

            job_industry_category wealth_segment deceased_indicator owns_car  \
customer_id                                                                    
1                          Health  Mass Customer                  N      Yes   
1                          Health  Mass Customer                  N      Yes   
1                          Health  Mass Customer                  N      Yes   
1                          Health  Mass Customer                  N      Yes   
1                          Health  Mass Customer                  N      Yes   
1                          Health  Mass Customer                  N      Yes   
1                          Health  Mass Customer                  N      Yes   
1                          Health  Mass Customer                  N      Yes   
1                          Health  Mass Customer                  N      Yes   
1                          Health  Mass Customer                  N      Yes   

             tenure  postcode            state  property_valuation  \
customer_id                                                          
1              11.0      2016  New South Wales                  10   
1              11.0      2016  New South Wales                  10   
1              11.0      2016  New South Wales                  10   
1              11.0      2016  New South Wales                  10   
1              11.0      2016  New South Wales                  10   
1              11.0      2016  New South Wales                  10   
1              11.0      2016  New South Wales                  10   
1              11.0      2016  New South Wales                  10   
1              11.0      2016  New South Wales                  10   
1              11.0      2016  New South Wales                  10   

                      brand product_line product_class product_size  \
customer_id                                                           
1                OHM Cycles     Standard        medium       medium   
1                     Solex     Standard        medium       medium   
1             Trek Bicycles         Road           low        small   
1            Norco Bicycles     Standard        medium       medium   
1                     Solex     Standard        medium       medium   
1            Giant Bicycles         Road        medium       medium   
1            Norco Bicycles     Mountain           low        small   
1            Giant Bicycles     Standard        medium       medium   
1            Giant Bicycles     Standard        medium       medium   
1                OHM Cycles         Road        medium       medium   

             list_price  standard_cost  
customer_id                             
1                235.63         125.07  
1               1577.53         826.51  
1               1720.70        1531.42  
1                360.40         270.30  
1                 71.49          53.62  
1               1538.99         829.65  
1                688.63         612.88  
1                230.91         173.18  
1                642.70         211.37  
1                742.54         667.40

In [50]:
customers['gender'] = customers['gender'].apply(lambda x:x[0].upper())

from datetime import datetime, timedelta
customers ['age'] = (datetime.now() - customers ['DOB']).apply(lambda x: x.days/365.25)

customers ['state'] = customers ['state'].apply(lambda x: x[0].upper())

customers = customers.drop('DOB', axis=1)



KeyError: 'gender'

In [29]:
customers = pd.get_dummies(data= customers, columns=['gender','job_industry_category', 'wealth_segment', 
                                                     'deceased_indicator', 'owns_car', 'state', 'brand','product_line','product_class','product_size',], drop_first=True)

In [30]:
customers = customers.groupby(level=0, as_index=True, dropna=True).mean()

In [31]:
customers.head(10)

past_3_years_bike_related_purchases  tenure  postcode  \
customer_id                                                          
1                                           93.0    11.0    2016.0   
2                                           81.0    16.0    2153.0   
4                                           33.0     7.0    4211.0   
6                                           35.0    13.0    3216.0   
7                                            6.0    11.0    2210.0   
9                                           97.0     8.0    2023.0   
11                                          99.0     9.0    3044.0   
12                                          58.0     8.0    4557.0   
13                                          38.0     8.0    3799.0   
14                                          85.0     6.0    2760.0   

             property_valuation   list_price  standard_cost        age  \
customer_id                                                              
1                          10.0   825.859091     551.487273  69.338809   
2                          10.0  1383.023333     640.936667  42.160164   
4                           9.0   523.860000     413.575000  61.363450   
6                           9.0  1186.338000     397.028000  56.410678   
7                           9.0   331.793333     258.423333  46.973306   
9                          12.0   892.925000     500.740000  49.930185   
11                          8.0  1129.906667     523.433333  68.791239   
12                          4.0   913.458571     407.740000  28.566735   
13                          6.0  1104.962857     485.337143  67.994524   
14                          8.0   836.463333     265.163333  39.890486   

             gender_M  gender_U  job_industry_category_Entertainment  ...  \
customer_id                                                           ...   
1                 0.0       0.0                                  0.0  ...   
2                 1.0       0.0                                  0.0  ...   
4                 1.0       0.0                                  0.0  ...   
6                 1.0       0.0                                  0.0  ...   
7                 0.0       0.0                                  0.0  ...   
9                 0.0       0.0                                  0.0  ...   
11                1.0       0.0                                  0.0  ...   
12                1.0       0.0                                  0.0  ...   
13                1.0       0.0                                  0.0  ...   
14                0.0       0.0                                  0.0  ...   

             brand_Solex  brand_Trek Bicycles  brand_WeareA2B  \
customer_id                                                     
1               0.181818             0.090909        0.000000   
2               0.000000             0.000000        0.666667   
4               0.500000             0.000000        0.000000   
6               0.000000             0.200000        0.400000   
7               0.000000             0.333333        0.333333   
9               0.500000             0.000000        0.166667   
11              0.166667             0.000000        0.500000   
12              0.142857             0.000000        0.142857   
13              0.285714             0.142857        0.285714   
14              0.000000             0.000000        0.000000   

             product_line_Road  product_line_Standard  product_line_Touring  \
customer_id                                                                   
1                     0.272727               0.636364              0.000000   
2                     0.000000               1.000000              0.000000   
4                     0.000000               1.000000              0.000000   
6                     0.000000               1.000000              0.000000   
7                     0.000000               0.666667              0.000000   
9                     0.

In [32]:
from sklearn.model_selection import train_test_split

In [41]:
X = customers.drop(['past_3_years_bike_related_purchases'], axis=1)
y = customers['past_3_years_bike_related_purchases']

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [43]:
from sklearn.tree import DecisionTreeClassifier

In [44]:
dtc = DecisionTreeClassifier()

In [45]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [46]:
pred = dtc.predict(X_test)

In [47]:
from sklearn.metrics import classification_report, confusion_matrix

In [48]:
print(classification_report(pred, y_test))

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         4
         1.0       0.10      0.14      0.12         7
         2.0       0.00      0.00      0.00        14
         3.0       0.00      0.00      0.00         7
         4.0       0.00      0.00      0.00        17
         5.0       0.00      0.00      0.00        10
         6.0       0.00      0.00      0.00        12
         7.0       0.12      0.17      0.14         6
         8.0       0.00      0.00      0.00         2
         9.0       0.00      0.00      0.00        10
        10.0       0.00      0.00      0.00        12
        11.0       0.00      0.00      0.00         3
        12.0       0.00      0.00      0.00         6
        13.0       0.00      0.00      0.00         9
        14.0       0.00      0.00      0.00        12
        15.0       0.00      0.00      0.00        17
        16.0       0.07      0.14      0.09         7
        17.0       0.00    

In [49]:
print(confusion_matrix(pred, y_test))

[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 [1 0 0 ... 0 0 0]]
